[Internal] Soft-deprecate the original sdk build scripts

diff --git a/script/android-sdk b/script/android-sdk
--- a/script/android-sdk
+++ b/script/android-sdk
@@ -1,5 +1,35 @@
 #!/bin/bash
 
+function usage {
+  #echo "$0 <task> <options>"
+  #echo "  tasks:"
+  #echo "    gen_release|gen|g         : generate the release"
+  echo "The original build scripts are no longer valid.  Please try the following three new scripts:"
+  echo ""
+  echo "    script/android_build           : generate the release"
+  echo "      options:"
+  echo "        -nt                    : do not run the unit tests"
+  echo "        -v=<VERSION>            : update the version to <VERSION> where <VERSION> is in the form [0-9]+.[0-9]+.[0-9]+"
+  echo "        -rc=<CANDIDATE>         : set the release candidate number to <CANDIDATE>"
+  echo ""
+  echo "    script/android_publish_rc      : publish the generated RC to Box"
+  echo "      options:"
+  echo "        -v=<VERSION>           : update the version to <VERSION> where <VERSION> is in the form [0-9]+.[0-9]+.[0-9]+"
+  echo "        -rc=<CANDIDATE>        : set the release candidate number to <CANDIDATE>"
+  echo "        -box-dir=<BOXDIR>      : the directory of your local synced Box account"
+  echo ""
+  echo "    script/android_publish_release : promote the latest published RC to Full Release"
+  echo "        -v=<VERSION>           : update the version to <VERSION> where <VERSION> is in the form [0-9]+.[0-9]+.[0-9]+"
+  echo "        -rc=<CANDIDATE>        : set the release candidate number to <CANDIDATE>"
+  echo "        -box-dir=<BOXDIR>      : the directory of your local synced Box account"
+  echo "If these scripts don't exist, run a 'make install'.  Make sure your submodules are init'ed and updated"
+  echo "Are you getting a doxygen error? make sure you have doxygen installed ('brew install doxygen')"
+  #echo "OLD: For example, to generate, tag, and publish the release candidate for the latest version: $0 pub -rc -push"
+  #echo "OLD: To mark the latest release candidate as the release version: $0 pub -push"
+}
+usage
+exit 1
+
 BEGIN_DIR=`pwd`
 SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 PLATFORM_NAME="Android"
