add verify step to make sure all contents exist

diff --git a/script/android-sdk b/script/android-sdk
--- a/script/android-sdk
+++ b/script/android-sdk
@@ -33,6 +33,13 @@ function complete_docs {
   cd "${currdir}"
 }
 
+function custom_verify {
+  if [[ ! ( -f "${ZIP_BASE}/${JAR_NAME}" ) ]]; then
+    echo "ERROR: jar not included"
+    exit 1
+  fi
+}
+
 function custom_gen {
   currdir=`pwd`
 
